### ISSUE TITLE
header-only libraries

### ISSUE THREAD

**Issue by onqtam** [RWTH-ELP/CMake-codecov#2]
I couldn't find a way to use the macros for a header-only library - I wanted to have a few executables exercising the coverage only in the header - I tried this:

```CMake
add_library(dummy STATIC foo2.h)
set_target_properties(dummy PROPERTIES LINKER_LANGUAGE CXX)
add_coverage(dummy)
```

and had a few tests added with ```add_test``` but their targets had not ```add_coverage()``` called for them (intentionally)

**Comment by alehaa** [comment]
I'm not sure, if this is the right way to define a header-only library. I think it must be somethink like this _in recent CMake versions_:
```CMake
add_library(dummy INTERFACE)
target_include_directories(dummy INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
```

But anyway: Thus this library won't be compiled, no coverage data can be generated for this library. You have to attach ```add_coverage()``` to the target, which uses the header-only library:
```CMake
add_executable(uses_dummy uses_dummy.c)
target_link_libraries(uses_dummy dummy)
add_coverage(uses_dummy)
```

I've added a demo for this case in the current master, maybe this will help you.
