### ISSUE TITLE
kind license change request

### ISSUE THREAD

**Issue by beku** [RWTH-ELP/CMake-codecov#7]
The project looks quite good. However, I can't use it in most of my github projects due to the restriction to GPL only license. Would it be considerable for you to change the license to something very liberal, so it becomes a no brainer for most project maintainers to add your cmake code to their projects?

**Comment by alehaa** [comment]
I see, the GPL is a little bit restrictive. The intention was, that changes made by others have to be public. As far as I know this should be covered by the LGPL, too - so you could link it anywhere as long as you publish changes to CMake-codecov code. Would this be enough for you?

**Comment by beku** [comment]
Your intention is quite reasonable. Still, my problem is primarily a psychological one. That I have to explain stuff like this to people from other industries. They are users, maintainers, lawyers etc.. And they might have some learning ahead, to wrap their mind around the various open source licenses, at which point they easily stop considering because of the cost involved.

To the legal side: Adding a helper like your cmake files to a project does not make the projects code dependent on GPL. It is even possible to give your cmake files in modified form to customers under the GPL and do not need to publish changes back to upstream. The GPL only requires to give changes to users of GPL code. (And if those users decide to publish your modified cmake files, e.g. to discuss with you, that's on their discretion.)

**Comment by alehaa** [comment]
Do you have a preffered license?

**Comment by beku** [comment]
BSD or MIT like this script here:
https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake

**Comment by alehaa** [comment]
Sorry, forgot to close the issue.

Re-licensed in 0322bcf0b5b38302dc89ffef25293972696d2d5b to 3-clause BSD.
